### PR TITLE
Update docker.sbt + entrypoint to fix 3.1.0-0.1RC1

### PR DESCRIPTION
**Pull request by 8ear**
Fix docker.sbt with the correct user (cortex != thehive) and fix the gid for the group to have the same as the standard docker group.

### CODE REVIEW

**Comment by To-om** [comment]
Thank you for your PR. I've manually merged into develop branch (I've change uid from 999 to 1001).

**Comment by garanews** [comment]
@8ear  confirmed working, thanks :)

**Comment by 8ear** [comment]
Hi @To-om,
It is very important that the  GID must be 999. Because it is the stanard GID for docker. So the docker.sock file has directly the correct permissions.

**Comment by To-om** [comment]
You are right the GID is important otherwise Cortex service won't be able to connect to Docker daemon.
I don't know which distribution you use but in Debian package, docker group is created without setting the GID (`groupadd --system docker` => the higher available GID less that 1000 is used). In my Ubuntu, the GID of docker is 998. I don't know what is the best solution to address this problem.

**Comment by 8ear** [comment]
Let me think a little about that and experiment a little bit ok?
In which branch you will have ma PR if I am ready?

**Comment by To-om** [comment]
I merged PR in develop branch

**Pull request closed without merging**
