### PR TITLE
GroupUserMapper.scala: Backport fix from TheHive for group mapper functionality

### PR DESCRIPTION
**Pull request by jiprocha**
This commit fixes issue #344 by backporting fix from TheHive repository. Original pull request from which the backport was taken can be found at https://github.com/TheHive-Project/TheHive/pull/1112.

### CODE REVIEW

**Comment by fkolacek** [comment]
+1 for fixing this please

**Comment by JakubOnderka** [comment]
This fix will also solve our problem. @jiprocha Thanks!

**Comment by eviltik** [comment]
Does the version 3.1.7 include this fix ? ty

**Comment by jiprocha** [comment]
@eviltik It does not, this is still pending to review, merge and release from the maintainers of Cortex. You can however clone 3.1.7 version of the repository, apply this patch and manually compile following the guide in documentation and it will work.

I've tried to reach out to the maintainers via email, without any response so far.

**Comment by nicocti** [comment]
Same here. Any news from the maintainers ?

**Comment by nadouani** [comment]
Hi all, we are going to evaluate this feature for the upcoming release.

**Pull request merged**
